baseURL = "http://example.com"
languageCode = "en-us"
title = "Yihao"
theme = "yblog"

pygmentsUseClasses = true

[Permalinks]
    blog = "/:filename/"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 2

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3

  [[menu.main]]
    name = "Projects"
    url = "/projects"
    weight = 4
    
[params]
  footer = [
    "Made with [Hugo](https://gohugo.io/)",
    "Content in [GitHub](#)"
  ]
